### ISSUE TITLE
How to use other UserStores?

### ISSUE THREAD

**Issue by ttutko** [Nordes/IdentityServer4.LdapExtension#19]
I have identityserver4 setup and was able to get your library to support authenticating against ActiveDirectory. This works when using InMemory UserStore but what I am looking to do is authenticate against ActiveDirectory and then store the user in a database specific to my application. My ultimate objective is to get this working with AspNet.Identity.MongoDbCore but I'm not sure how to even get this working with AspNetCore's built-in EF provider. I am looking for guidance on how to use your library for authentication only but not as the userstore?

**Comment by Nordes** [comment]
Hi, sorry for the delay. 

Regarding the IdentityServer4, you have a setup for the official storage. This plugin/extension is IS configuration in order to validate the credentials towards a LDAP server. The current userstore is configurable regarding the caching (Redis/InMemory). It can then be used in conjunction with the IS database configuration.

If you want to implement the user caching within mongo (which is maybe not the best decision due to performance), you can base yourself on the Redis implementation.

For the IS4 with MongoDb instead of Postgres or MS SQL, please refer to the official IS4 site or stackoverflow questions.

Thank you.

**Comment by cheoalfredo** [comment]
Sorry @Nordes , just in case i did not understand what you're talkin about, what if i want to use is4 with a sql server (EF) and with ldap plugin, can that be done ?
