### ISSUE TITLE
How to get data info from AD profiles like emails, name, etc from scopes?

### ISSUE THREAD

**Issue by biapar** [Nordes/IdentityServer4.LdapExtension#47]
How to get data info from AD profiles like emails, name, etc from scopes?

**Comment by Nordes** [comment]
Hi @biapar , could you be more specific? But I think you want to refer to claims and scope which is more an Identity Server thing. You can then look in the IS4 documentation.

Otherwise, this library uses some LDAP attributes (ActiveDirectory attributes) by default. You can implement your own if you wish to.

**Comment by biapar** [comment]
Hi, yes I mean AD Attributes other standard claims.

**Comment by chrgraefe** [comment]
Hi @biapar

you can get the email via default scope "email" 

put in Startup.cs
```csharp
options.Scope.Add("email");
```

don't forget to allow the scope in client configuration
```csharp
AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    }
```

**Comment by Nordes** [comment]
Thanks @chrgraefe
