### ISSUE TITLE
Active Directory Ldap Test

### ISSUE THREAD

**Issue by murattdogan** [Nordes/IdentityServer4.LdapExtension#5]
Hello, is your project time to test with Active Directory Ldap? This matter is important to me, I want to use your refusal. Thank you from now.

**Comment by Nordes** [comment]
Hi,

I am quite busy recently and I want to specify that I am on a different
timezone than you.

Since I use this extension at work with a default active directory, it
works perfectly without any issue. At home I use openldap and it also
works. For your issues I have to analyze or you can also help by doing some
analysis.

Note that you can also have a custom provider for the ldap. I mean by that,
that you can map your own ldap attributes to your openid stuff. I have 2
that exists in the project as example (active directory and open ldap).

I'll try to find some time tomorrow to check your full story.

Best,

Nordès

**Comment by murattdogan** [comment]
if you want, I can give you a remote connection.
phone number 0545 858 25 58 We can also contact you via whatsap

**Comment by Nordes** [comment]
Please read my comment in the issue #4

**Comment by Nordes** [comment]
If you want to do a remote connection, it could be feasible, however I am in the Japan timezone and I am available only from 9PM (local time).

**Comment by murattdogan** [comment]
Turkey to discuss Japan are also 3PM hour clock 9pm. How to communicate for remote connection. I'll wait to hear from you.

**Comment by murattdogan** [comment]
"ldapActiveDirectory": {
    // Active directory
    "url": "ip Adress",
    "port": 389,
    "ssl": false,
    "bindDn": "Domain\\Administrator",
    "bindCredentials": "DomaninPassword",
    "searchBase": "DC=hitit,DC=edu,DC=tr",
    // "searchFilter": "(&(objectClass=user)(objectClass=person)(sAMAccountName={0}))",
    "searchFilter": "(&(objectClass=user)(sAMAccountName={0}))"
    // "searchFilter": "(&(objectClass=user)(objectClass=person)(sAMAccountName={0}))",
    // Example: If you use a redis instead of in-memory
    //"redis": "localhost:32771,ssl=false"
  }
Problem solved . The ldap config is faulty. Rather above

**Comment by murattdogan** [comment]
If you add this project to my project, I would like to join and develop myself in the active directory part

**Comment by Nordes** [comment]
I tried to add you on whatsapp but without success.
