### ISSUE TITLE
Is there a reset password feature here yet?

### ISSUE THREAD

**Issue by wickstargazer** [Nordes/IdentityServer4.LdapExtension#61]
Hi,

Would like to know if there is a reset password feature for this library?

**Comment by Nordes** [comment]
No, reset password is not part of this extension. For this you would need to implement it yourself. This is not that hard to implement. Basically you need to add some UI stuff and then handle it in your code (e.g.: ask for email +question then search in the AD or a database for it, then have a NON read-only AD user and then update the password with a random one). But for the reset password you would need a special token stored in your database so that when the user click on the mail a flow kicks in and you handle it.

Again, that being said, this is way out of scope for this extension.
