### ISSUE TITLE
IdentityServer version 4.1.2

### ISSUE THREAD

**Issue by itoop2019** [Nordes/IdentityServer4.LdapExtension#65]
Hello!
I tried to update your example to IdentityServer version 4.1.2 and it didn’t work for me, are you planning to update your IdentityServer.LdapExtension?

**Comment by Nordes** [comment]
I will look at it, I have to re-setup my whole pc ;). My previous one is not working anymore. So I will look lightly to how to upgrade the package. I might also have to upgrade the build to use github actions.

**Comment by Nordes** [comment]
4.1.2 is not the official release (at least with a tag). I will try to upgrade based on the base code I can see in the repo. I don't really know all the changes between 4.1.2 and 4.1.1. Also, note that IdentityServer4 will be maintained (bug fixes) until 2022 (see official website).

**Comment by Nordes** [comment]
After some review of the code, I had to recreate the project from scratch (sample). The main reason was due to major change in how the project was made. I was able to re-setup the whole shabang without needing to create my own AD. The new IdentityServer quickstarts also have some extra profiling that I didn't implement in my extension. Since it's working without such thing, it shouldn't be a big issue.

**Upgrades are:**
1. Use free AD (e.g.: https://www.zflexldapadministrator.com/index.php/blog/82-free-online-ldap) for tests
2. Reconfigure the appsettings.json
3. Run
4. Test with a guest account (see on the web).
5. Upgrade all to .Net 5.0 (Extension and etc.) -- Ldap extension could target both 3.x and 5.
6. Add a new console api test

I will create a branch before merging the changes in my project.
![image](https://user-images.githubusercontent.com/446572/114477103-a1c97b80-9bc9-11eb-8a0e-d43066cd0427.png)

https://github.com/Nordes/IdentityServer4.LdapExtension/tree/is_4_1_2

**Comment by itoop2019** [comment]
Hi, 
that's cool!
Thanks, I already thought that you are not supporting your project!

**Comment by Nordes** [comment]
Yes, I know ;). This year was quite a busy year (personal life, jobs and moving again). I am still quite busy this week, but I'll try to merge somehow soon.

**Comment by Nordes** [comment]
New version of the package is now available: https://www.nuget.org/packages/IdentityServer.LdapExtension/

However, the symbols failed to be published (Don't ask why... I need to change the AppVeyor for Github actions ;) )
