### ISSUE TITLE
Can we combine openldap vs active directory in a single attribute

### ISSUE THREAD

**Issue by murattdogan** [Nordes/IdentityServer4.LdapExtension#7]
.AddLdapUsers<ActiveDirectoryAppUser>(Configuration.GetSection("ldapActiveDirectory"),
                    UserStore.InMemory);
            //.AddLdapUsers<OpenLdapAppUser>(Configuration.GetSection("ldapOpenLdap"), UserStore.InMemory)

**Comment by Nordes** [comment]
Sorry for very late reply,

No, not really, both are fundamentally different. OpenLdap have completely different attributes (as Samba does). Please open the implementation, normally you should see what I mean. I think that some simplification in the project could be added, it wouldn't hurt, for sure.

The code makes it possible to also add your own "AddLdap" ... or instead of inMemory/redis use your own provider. Details should be added within the Wiki. For now I have no time for that, I am sorry.

**Comment by Nordes** [comment]
Please close the issue if you consider the answer ok.

**Comment by murattdogan** [comment]
I'm trying to query openldap and active directory ldap with a single Ldap AppUser. In our structure Open Ldap student Academic Staff Active Dricetory Ldap have I want to combine these two applications. So how do we do it with MultipleLdapAppUser.

**Comment by Nordes** [comment]
If you want to do it, you need to write your own custom IAppUser implementation. See the code for ActiveDirectoryAppUser.cs 

The file `ActiveDirectoryLdapAttributes.cs` is a way to get the attributes from AD with the AD well known attributes. The same goes for the OpenLdap (if the proper setup is done on the OpenLdap Server).

When you will be merging ActiveDirectory and OpenLdap users attributes, you will have to know from where they come from before in order to fill your user information properly. As said in the #10 , you have specific fields that you know exists on one system and not the other. For that, I would recommend you to re-validate using the username in your `CustomAppUser: IAppUser`.

Normally, you should be able to inject the multi-configurations of ldap and redo a validation using the Regex expression (multiple ldap config). 

Example (pseudo code):
```c#
public class MyCustomSuffLdapAppUser: IAppUser{
        public MyCustomSuffLdapAppUser(ExtensionConfig config)
        {
            _config = config;
        }
       public void FillClaims(LdapEntry user){
         /// later in a different method
         config.Connections.ToList().FirstOrDefault(f=> f.IsConcerned(Username)); // Give if the first connection that concern the user
         // ... your own custom code here in order to map your attributes
        // Note that there's a new property added for each configuration and it's the friendlyName.
        // Use that in a switch statement and if you have an enum to even be sure it's easy to track everywhere? (maybe), then please do that.
       // Your claims are mapped! Yay, thank you, please see the existing code. It should be feasible
      }
 
      // ...
}
```
